### ISSUE TITLE
Apple SUS Checkin issue

### ISSUE THREAD

**Issue by Zolotkey** [salopensource/sal-scripts#74]
I have a few clients that are failing to checkin because the Apple SUS checkin module has this error and kills the whole checkin from sending to the server.

Currently this is on a 10.11.6 (15G22010) Machine running Sal-Scripts 3.1.1.

/usr/local/sal/bin/sal-submit
Traceback (most recent call last):
  File "/usr/local/sal/checkin_modules/apple_sus_checkin.py", line 179, in <module>
    main()
  File "/usr/local/sal/checkin_modules/apple_sus_checkin.py", line 20, in main
    sus_submission['facts'] = get_sus_facts()
  File "/usr/local/sal/checkin_modules/apple_sus_checkin.py", line 68, in get_sus_facts
    result['last_check'] = _get_log_time(line).isoformat()
AttributeError: 'NoneType' object has no attribute 'isoformat'

**Comment by grahamgilbert** [comment]
Does this work on any 10.11 machines? I doubt this has been tested on operating systems that old. Regardless, we should log the error and move on.

**Comment by sheagcraig** [comment]
Ooof. Yeah, I would grab one of those machines and throw some explicit handling in for places where it fails.

I'll put some handling in the main sal scripts so the whole thing doesn't bomb, but I don't have any 10.11 machines to do more specific testing with, so I'm going to have to rely on others for that.

**Comment by Zolotkey** [comment]
@grahamgilbert I do have 2 10.11 Machines reporting in this morning. But the error output is the same. I am looking into it further to see if I can find the difference between the two.
